logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: off
LineFitGymApp:
    default:
        admin:
            pass: ${DEFAULT_ADMIN_PASS:topsecret}
    remember:
        me:
            key: ${REMEMBER_ME_KEY:topsecret}
spring:
    application:
        name: LineFitGymApp

    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ${MYSQL_PASSWORD:1234}
        url: jdbc:mysql://localhost:3306/onlinefitgym_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        username: ${MYSQL_USER:root}
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQLDialect
                format_sql: true


    mvc:
        hiddenmethod:
            filter:
                enabled: true

app:
    token:
        secretKey: ${TOKEN_SECRET:4b3vDCnoeTDwwgIn0cYQw83cZbI27z+BY+bDFyQHo3+8IZw7hzMn9aqWkI31ExwAYX/nSjwJnkRgOTF82VIAsQ==}







