logging:
  level:
    root: info
    org.springframework: info
    org.springframework.security: off
    com.linefit.linefitgymapp: debug


LineFitGymApp:
  default:
    admin:
      pass: ${DEFAULT_ADMIN_PASS}

cloudinary:
  cloud_name: danjpzd8z
  api_key: 759599338768339
  api_secret: ${SECRET}

spring.mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true


rapidapi:
  key: ${RAPIDAPI_KEY}

spring:
  application:
    name: LineFitGymApp
  remember:
    me:
      key: ${REMEBER_ME_KEY}

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/onlinefitgym_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${MYSQL_USER}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


  mvc:
    hiddenmethod:
      filter:
        enabled: off

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
  # change load path to resource folder instead of /target
    prefix: classpath:/templates/

  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 0
  servlet:
    multipart:
      max-file-size: 12MB
      max-request-size: 12MB

