logging:
  level:
    root: info
    org.springframework: info
    com.linefit.linefitgymapp: debug

LineFitGymApp:
  default:
    admin:
      pass: ${DEFAULT_ADMIN_PASS:topsecret}

spring:
  application:
    name: LineFitGymApp
  remember:
    me:
      key: ${REMEBER_ME_KEY:topsecret}

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ${MYSQL_PASSWORD:1234}
    url: jdbc:mysql://localhost:3306/onlinefitgym_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true


  mvc:
    hiddenmethod:
      filter:
        enabled: off